language: python
python:
  - 2.7
  - 3.6
dist: trusty
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
cache: pip

before_script:
  - pip install flake8
script:
  # Code quality check
  - flake8
