# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This workflow will install Python dependencies, run tests, lint and rat with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout SupportScripts
      uses: actions/checkout@v2
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support

    - name: Checkout Spinnaker Dependencies
      run: |
        support/gitclone2.sh https://github.com/SpiNNakerManchester/SpiNNUtils.git
        support/gitclone2.sh https://github.com/SpiNNakerManchester/SpiNNMachine.git
        support/gitclone2.sh https://github.com/SpiNNakerManchester/SpiNNMan.git
        support/gitclone2.sh https://github.com/SpiNNakerManchester/PACMAN.git
        support/gitclone2.sh https://github.com/SpiNNakerManchester/DataSpecification.git
        support/gitclone2.sh https://github.com/SpiNNakerManchester/spalloc.git
        support/gitclone2.sh git://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git
        support/gitclone.sh https://github.com/SpiNNakerManchester/sPyNNaker.git
        support/gitclone.sh https://github.com/SpiNNakerManchester/sPyNNaker8.git

    - name: Install -pip
      run: |
        python -m pip install --upgrade pip
        pip install 'pylint<2.5' flake8

    - name: Install SpiNNUtils
      run: python setup.py install
      working-directory: SpiNNUtils

    - name: Install SpiNNMachine
      run: python setup.py install
      working-directory: SpiNNMachine

    - name: Install SpiNNMan
      run: python setup.py install
      working-directory: SpiNNMan

    - name: Preinstall pacman requirements (2.7 Only)
      if: matrix.python-version == 2.7
      run: pip install -r requirements.txt
      working-directory: PACMAN

    - name: Install PACMAN
      run: python setup.py install
      working-directory: PACMAN

    - name: Install DataSpecification
      run: python setup.py install
      working-directory: DataSpecification

    - name: Install spalloc
      run: python setup.py install
      working-directory: spalloc

    - name: Preinstall SpiNNFrontEndCommon requirements (2.7 Only)
      if: matrix.python-version == 2.7
      run: pip install -r requirements.txt
      working-directory: SpiNNFrontEndCommon

    - name: Install SpiNNFrontEndCommon
      run: python setup.py install
      working-directory: SpiNNFrontEndCommon

    - name: Preinstall sPyNNaker requirements (2.7 Only)
      if: matrix.python-version == 2.7
      run: pip install -r requirements.txt
      working-directory: sPyNNaker

    - name: Install sPyNNaker
      run: python setup.py install
      working-directory: sPyNNaker

    - name: Preinstall sPyNNaker8 requirements (2.7 Only)
      if: matrix.python-version == 2.7
      run: pip install -r requirements.txt
      working-directory: sPyNNaker8

    - name: Install sPyNNaker8
      run: python setup.py install
      working-directory: sPyNNaker8

    - name: Lint with flake8
      run: |
        # run flake8
        flake8 examples
    - name: Lint with pylint
      # Broken in 2.7 as it can not find data_specification.exceptions
      if: matrix.python-version != 2.7
      # Note that there's special conditioning of the return code of pylint
      run: |
        pylint --output-format=colorized --disable=R,C examples || exit $(($? & 35))

    - name: Run rat copyright enforcement
      if: matrix.python-version == 3.6
      run: |
        support/rat.sh download
        support/rat.sh run
